# Generated by Django 5.0.6 on 2024-06-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockflow', '0002_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contac',
            new_name='contact',
        ),
    ]
