# Generated by Django 5.0.6 on 2024-06-13 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockflow', '0003_rename_contac_supplier_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
