# Generated by Django 5.0.6 on 2024-06-13 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockflow', '0004_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be numeric and can include +, - symbols', regex='^[0-9+\\-]+$')]),
        ),
    ]
